CREATE TABLE cads.alert_mst (
    id NUMERIC NOT NULL,
    source_system VARCHAR(250) NOT NULL,
    due_time VARCHAR(50),
    priority NUMERIC,
    alert_type VARCHAR(500),
    business_unit VARCHAR(50) NOT NULL,
    business_user VARCHAR(20),
    rule_set VARCHAR(500),
    txn_id VARCHAR(250) NOT NULL,
    last_updated_date TIMESTAMP DEFAULT CURRENT_TIMESTAMP NOT NULL,
    created_by VARCHAR(50) DEFAULT 'System' NOT NULL,
    last_updated_by VARCHAR(50),
    amount NUMERIC,
    hit_count NUMERIC,
    currency VARCHAR(3),
    replyto_queue_name VARCHAR(50),
    request_number NUMERIC,
    reply_to_manager VARCHAR(500),
    value_date DATE,
    branch VARCHAR(500),
    last_transaction_date DATE,
    closed_date DATE,
    qa_status VARCHAR(50),
    direction VARCHAR(500),
    receiver VARCHAR(500),
    systemid VARCHAR(500),
    remaining_sanctions_matches NUMERIC,
    steps VARCHAR(50),
    closed_by VARCHAR(50),
    origination_branch VARCHAR(250),
    origination_region VARCHAR(250),
    is_post_positive_completed CHAR(1),
    application_alias_name VARCHAR(500),
    unique_transaction_reference VARCHAR(500),
    country_origination VARCHAR(500),
    country_intermediary VARCHAR(500),
    country_destination VARCHAR(500),
    last_stage VARCHAR(500),
    screening_type VARCHAR(500),
    screening_category VARCHAR(500),
    sector VARCHAR(500),
    business_line VARCHAR(500),
    product VARCHAR(500),
    sub_product VARCHAR(500),
    local_reference VARCHAR(500),
    transaction_date DATE,
    sender_bic VARCHAR(500),
    receiver_bic VARCHAR(500),
    payment_currency VARCHAR(500),
    queue_transition_date DATE,
    qa_closed_by VARCHAR(500),
    header_version CHAR(50),
    inquiry_step_identifier VARCHAR(50),
    business_id NUMERIC,
    original_debtor_name VARCHAR(500),
    beneficiary_account VARCHAR(500),
    ordering_customer_account VARCHAR(500),
    product_code VARCHAR(100),
    secondary_site VARCHAR(50),
    derived_step_identifier VARCHAR(250),
    branch_txn_id VARCHAR(250),
    l3_dual_review CHAR(3) DEFAULT 'No',
    research_type VARCHAR(500),
    updated_final_decision VARCHAR(50),
    udf1_datetime DATE DEFAULT NULL,
    screened_date DATE,
    org_citi_legal_vehicle VARCHAR(750),
    org_citi_legal_vehicle_type VARCHAR(100),
    dest_citi_legal_vehicle VARCHAR(750),
    dest_citi_legal_vehicle_type VARCHAR(100),
    dr_alert_id NUMERIC,
    uk_sanctions_authority VARCHAR(50),
    auto_dispose_matches CHAR(1),
    lapc_alert VARCHAR(50),
    citi_enabled CHAR(1),
    parent_alert_id NUMERIC,
    rescind_status VARCHAR(50),
    rmp_alert VARCHAR(250),
    rmp_prev_alertid NUMERIC,
    rmp_rules VARCHAR(50),
    rmp_csaw_instance VARCHAR(50),
    bulk_process_req_id NUMERIC,
    rtm_alert_id NUMERIC,
    is_urgent CHAR(1) DEFAULT 'N',
    partition_date DATE NOT NULL,
    step_identifier VARCHAR(250),
    classification VARCHAR(250),
    created_date DATE
);

CREATE TABLE cads.enhanced_search_fields (
    field_group VARCHAR(100) NOT NULL,
    field_name VARCHAR(100) NOT NULL,
    field_type VARCHAR(20) NOT NULL,
    display_order NUMERIC NOT NULL,
    gui_identifier VARCHAR(100) NOT NULL,
    created_by VARCHAR(50),
    created_date DATE,
    updated_by VARCHAR(50),
    updated_date DATE,
    is_active CHAR(1) NOT NULL,
    partition_date DATE,
    is_sortable CHAR(1) NOT NULL,
    collection_name VARCHAR(50),
    regex_enabled VARCHAR(1)
);

CREATE TABLE cads.gui_label (
    gui_identifier VARCHAR(100) NOT NULL,
    role_identifier VARCHAR(100) NOT NULL,
    label VARCHAR(1000),
    user_language VARCHAR(100) NOT NULL
);


CREATE TABLE cads.alert_det (
    id                          INTEGER         NOT NULL PRIMARY KEY,
    alert_id                    INTEGER         NOT NULL,
    field_name                  VARCHAR(4000)   NOT NULL,
    field_name_alias            VARCHAR(100)    NOT NULL,
    field_value_offset          INTEGER         NOT NULL,
    field_order                 INTEGER         NOT NULL,
    created_date                DATE            DEFAULT CURRENT_DATE,
    last_updated_date           DATE,
    created_by                  VARCHAR(50)     NOT NULL,
    last_updated_by             VARCHAR(50),
    version                     INTEGER,
    partition_date              DATE,
    field_value                 TEXT,           -- Changed to TEXT for large values
    is_field_value_clob         CHAR(1)         -- 'Y'/'N' flag
);

